server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  max_multipart_memory: 33554432  # 32MB in bytes

zeo:
  executable_path: "network"
  workdir: "./workspace"
  timeout: 5m

concurrency:
  max_workers: 0  # 0 = runtime.NumCPU()
  max_queue_size: 1000
  rate_limit_per_ip: 10  # requests per second
  max_file_size: 104857600  # 100MB in bytes
  max_concurrent_uploads: 50

cache:
  enabled: true
  ttl: 3600s
  max_size_mb: 1024
  shards: 32

logging:
  level: "info"
  format: "json"
  output: "stdout"